language: node_js
sudo: false
node_js:
  - 6
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - npm install --dev
script:
  - ./node_modules/.bin/karma start --browsers Firefox --single-run
